using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace GenUtilities;

[Generator]
public class ActionGenerator : IIncrementalGenerator {
	private const string Namespace = "GenUtilities";
	private const string ClassName = "Actions";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var projectFile = context.AdditionalTextsProvider
			.Where(file => file.Path.EndsWith("project.godot"))
			.Select((file, token) => file.GetText(token))
			.Collect();

		context.RegisterSourceOutput(projectFile, GenerateCode);
	}

	private void GenerateCode(SourceProductionContext context, ImmutableArray<SourceText?> texts) {
		var memberCode = new StringBuilder();
		foreach (var text in texts) {
			if (text == null) continue;
			var content = text.ToString();
			var inputs = GetActions(content);
			var fields = inputs.Select(CreateActionEntry);

			foreach (var field in fields) memberCode.AppendLine(field);
		}

		var code = $$"""
		             // <auto-generated/>

		             using System;
		             using Godot;

		             namespace {{Namespace}};

		             partial class {{ClassName}}
		             {
		             {{memberCode}}
		             }

		             """;
		context.AddSource($"{Namespace}.{ClassName}.g.cs", SourceText.From(code, Encoding.UTF8));
	}

	private static string CreateActionEntry(string action) {
		var actionKey = action.Replace("\"", "");
		var actionField = Regex.Replace(action, "[^a-zA-Z0-9]+", "");;
		return $"\tpublic static StringName {actionField} = \"{actionKey}\"; ";
	}

	private static List<string> GetActions(string content) {
		var result = new List<string>();
		var inputSection = false;
		foreach (var line in content.Split(['\n'])) {
			if (line.Equals("[input]"))
				inputSection = true;
			else if (line.StartsWith("[") && inputSection) break;

			if (!inputSection) continue;

			var keyValue = line.Split(['='], 2);
			if (keyValue.Length == 2) result.Add(keyValue[0].Trim());
		}

		return result;
	}
}
