using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GenUtilities;

[Generator]
public class AutowireGenerator : IIncrementalGenerator {
    private const string Namespace = "GenUtilities";
    private const string AttributeName = "Autowire";

    private const string AttributeSourceCode =
        $$"""
          // <auto-generated/>
          using System;

          namespace {{Namespace}}
          {
              [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
              public sealed class {{AttributeName}}Attribute : Attribute
              {
                  /// <summary>
                  /// Name of the field that refers to the Godot node (e.g. nameof(_title)).
                  /// </summary>
                  public string NodeFieldName { get; }

                  /// <summary>
                  /// Name of the member on the node to write to (e.g. nameof(Label.Text)).
                  /// </summary>
                  public string NodeMemberName { get; }

                  public {{AttributeName}}Attribute(string nodeFieldName, string nodeMemberName)
                  {
                      NodeFieldName = nodeFieldName;
                      NodeMemberName = nodeMemberName;
                  }
              }
          }
          """;

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        // Emit the [Autowire] attribute itself.
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource(
                "AutowireAttribute.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        var propertyProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetAutowireMembers(ctx))
            .Where(static result => result.attributeFound)
            .SelectMany(static (result, _) => result.members);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(propertyProvider.Collect()),
            static (spc, source) => Generate(spc, source.Left, source.Right));
    }

    private static (IEnumerable<PropertyDeclarationSyntax> members, bool attributeFound)
        GetAutowireMembers(GeneratorSyntaxContext context) {
        var classSyntax = (ClassDeclarationSyntax)context.Node;
        var members = classSyntax.Members;

        var autowiredProperties = new List<PropertyDeclarationSyntax>();

        foreach (var member in members.OfType<PropertyDeclarationSyntax>()) {
            if (HasAutowireAttribute(context.SemanticModel, member))
                autowiredProperties.Add(member);
        }

        return (autowiredProperties, autowiredProperties.Count > 0);
    }

    private static bool HasAutowireAttribute(SemanticModel model, PropertyDeclarationSyntax propertySyntax) {
        foreach (var attributeSyntax in propertySyntax.AttributeLists.SelectMany(a => a.Attributes)) {
            if (model.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue;

            var attributeTypeName = attributeSymbol.ContainingType.ToDisplayString();
            if (attributeTypeName == $"{Namespace}.{AttributeName}Attribute" ||
                attributeTypeName == $"{Namespace}.{AttributeName}") {
                return true;
            }
        }

        return false;
    }

    private sealed class ClassDefinition {
        public string NamespaceName { get; set; } = "";
        public string ClassName { get; set; } = "";
        public List<PropertyDefinition> Properties { get; } = new();
    }

    private sealed class PropertyDefinition {
        public string PropertyName { get; set; } = "";
        public string PropertyType { get; set; } = "";
        public string BackingValueFieldName { get; set; } = "";
        public string NodeFieldName { get; set; } = "";
        public string NodeMemberName { get; set; } = "";
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<PropertyDeclarationSyntax> properties) {
        var classes = new Dictionary<string, ClassDefinition>();

        foreach (var propertySyntax in properties) {
            if (propertySyntax.Parent is not ClassDeclarationSyntax classSyntax)
                continue;

            var semanticModel = compilation.GetSemanticModel(classSyntax.SyntaxTree);
            if (semanticModel.GetDeclaredSymbol(classSyntax) is not INamedTypeSymbol classSymbol)
                continue;

            if (semanticModel.GetDeclaredSymbol(propertySyntax) is not IPropertySymbol propertySymbol)
                continue;

            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var classKey = $"{namespaceName}.{className}";

            if (!classes.TryGetValue(classKey, out var classDef)) {
                classDef = new ClassDefinition {
                    NamespaceName = namespaceName,
                    ClassName = className
                };
                classes.Add(classKey, classDef);
            }

            var autowireAttribute = propertySymbol
                .GetAttributes()
                .First(attr =>
                    attr.AttributeClass?.ToDisplayString() == $"{Namespace}.{AttributeName}Attribute" ||
                    attr.AttributeClass?.ToDisplayString() == $"{Namespace}.{AttributeName}");

            // Read constructor arguments: Autowire(nameof(_title), nameof(Label.Text))
            var nodeFieldName = autowireAttribute.ConstructorArguments.Length > 0
                ? autowireAttribute.ConstructorArguments[0].Value as string ?? ""
                : "";

            var nodeMemberName = autowireAttribute.ConstructorArguments.Length > 1
                ? autowireAttribute.ConstructorArguments[1].Value as string ?? ""
                : "";

            if (string.IsNullOrWhiteSpace(nodeFieldName) || string.IsNullOrWhiteSpace(nodeMemberName))
                continue;

            var propertyName = propertySymbol.Name;
            var propertyType = propertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            // Backing value field: _titleVal for property `Title`.
            var backingValueFieldName = $"_{char.ToLowerInvariant(propertyName[0])}{propertyName.Substring(1)}Val";

            classDef.Properties.Add(new PropertyDefinition {
                PropertyName = propertyName,
                PropertyType = propertyType,
                BackingValueFieldName = backingValueFieldName,
                NodeFieldName = nodeFieldName,
                NodeMemberName = nodeMemberName
            });
        }

        foreach (var classDef in classes.Values) {
            GenerateClass(context, classDef);
        }
    }

    private static void GenerateClass(SourceProductionContext context, ClassDefinition def) {
        var fieldsBuilder = new StringBuilder();
        var methodsBuilder = new StringBuilder();
        var refreshBodyBuilder = new StringBuilder();

        foreach (var prop in def.Properties) {
            // Example:
            // private string _titleVal = "";
            fieldsBuilder.AppendLine(
                $"        private {prop.PropertyType} {prop.BackingValueFieldName} = default!;");

            // Example:
            // private void UpdateTitle(string value) {
            //     _titleVal = value;
            //     if (IsNodeReady()) {
            //         _title.Text = value;
            //     }
            // }
            methodsBuilder.AppendLine(
                $@"        private void Update{prop.PropertyName}({prop.PropertyType} value)
        {{
            {prop.BackingValueFieldName} = value;
            if (IsNodeReady())
            {{
                {prop.NodeFieldName}.{prop.NodeMemberName} = value;
            }}
        }}

");

            // For RefreshAllComponents
            refreshBodyBuilder.AppendLine(
                $"            Update{prop.PropertyName}({prop.BackingValueFieldName});");
        }

        if (def.Properties.Count == 0)
            return;

        var source = $$"""
                       // <auto-generated/>
                       #nullable enable

                       namespace {{def.NamespaceName}};

                       public partial class {{def.ClassName}}
                       {
                       {{fieldsBuilder}}

                               private void RefreshAllComponents()
                               {
                       {{refreshBodyBuilder}}
                               }

                       {{methodsBuilder}}
                       }
                       """;

        context.AddSource($"{def.ClassName}.Autowire.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
