using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GenUtilities;

[Generator]
public class BindGenerator : IIncrementalGenerator {
	private const string Namespace = "GenUtilities";
	private const string AttributeName = "Bind";

	private const string AttributeSourceCode = $@"// <auto-generated/>

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field)]
    public class {AttributeName} : System.Attribute
    {{
    }}
}}";

	public void Initialize(IncrementalGeneratorInitializationContext context) {
		context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
			"BindAttribute.g.cs",
			SourceText.From(AttributeSourceCode, Encoding.UTF8)));

		var propertyProvider = context.SyntaxProvider
			.CreateSyntaxProvider(
				(s, _) => s is ClassDeclarationSyntax,
				(ctx, _) => GetDeclarationForSourceGen(ctx))
			.Where(t => t.attributeFound)
			.SelectMany((t, _) => t.Item1);

		context.RegisterSourceOutput(context.CompilationProvider.Combine(propertyProvider.Collect()),
			(ctx, value) => GenerateCode(ctx, value.Left, value.Right));
	}

	private static (IEnumerable<MemberDeclarationSyntax>, bool attributeFound) GetDeclarationForSourceGen(
		GeneratorSyntaxContext context) {
		var classSyntax = (ClassDeclarationSyntax)context.Node;
		var members = classSyntax.Members;
		var foundMembers = members.Select(member => IsBindAttributeOnMember(context.SemanticModel, member))
			.Where(syntax => syntax != null)
			.ToList();
		return (foundMembers!, foundMembers.Count > 0);
	}


	private static MemberDeclarationSyntax? IsBindAttributeOnMember(SemanticModel model,
		MemberDeclarationSyntax declarationSyntax) {
		foreach (var attributeSyntax in declarationSyntax
			         .AttributeLists
			         .SelectMany(attributeListSyntax => attributeListSyntax.Attributes)) {
			if (model.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
				continue;

			var attributeName = attributeSymbol.ContainingType.ToDisplayString();
			if (attributeName == $"{Namespace}.{AttributeName}")
				return declarationSyntax;
		}

		return null;
	}

	private class ClassDefinition {
		public string NamespaceName { get; set; } = "";
		public string ClassName { get; set; } = "";
		public HashSet<string> UsingNamespaceName { get; set; } = [];

		public List<MemberDefinition> MemberDefinitions { get; } = [];
	}

	private class MemberDefinition {
		public string Type { get; set; } = "";
		public string Name { get; set; } = "";
	}

	private void GenerateCode(SourceProductionContext context, Compilation compilation,
		ImmutableArray<MemberDeclarationSyntax> members) {
		Dictionary<string, ClassDefinition> classDefinitions = [];

		foreach (var member in members)
			if (member.Parent is ClassDeclarationSyntax classDeclarationSyntax) {
				var semanticModel = compilation.GetSemanticModel(classDeclarationSyntax.SyntaxTree);
				if (semanticModel.GetDeclaredSymbol(classDeclarationSyntax) is not INamedTypeSymbol classSymbol)
					continue;

				var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
				var className = classDeclarationSyntax.Identifier.Text;
				var key = $"{namespaceName}.{className}";
				if (!classDefinitions.ContainsKey(key)) classDefinitions[key] = new ClassDefinition();

				var classDefinition = classDefinitions[key];
				classDefinition.ClassName = className;
				classDefinition.NamespaceName = namespaceName;
				if (member is FieldDeclarationSyntax field) {
					var variable = field.Declaration.Variables[0];

					// Get the Type of the field.
					if (semanticModel.GetDeclaredSymbol(variable) is not IFieldSymbol fieldSymbol) continue;

					var memberDefinition = new MemberDefinition {
						Name = fieldSymbol.Name,
						Type = fieldSymbol.Type.Name
					};
					classDefinition.MemberDefinitions.Add(memberDefinition);
					classDefinition.UsingNamespaceName.Add(fieldSymbol.Type.ContainingNamespace.ToDisplayString());
				} else if (member is PropertyDeclarationSyntax property) {
					if (semanticModel.GetDeclaredSymbol(property) is not IPropertySymbol propertySymbol) continue;

					var memberDefinition = new MemberDefinition {
						Name = propertySymbol.Name,
						Type = propertySymbol.Type.Name
					};
					classDefinition.MemberDefinitions.Add(memberDefinition);
					classDefinition.UsingNamespaceName.Add(propertySymbol.Type.ContainingNamespace.ToDisplayString());
				}
			}

		foreach (var definition in classDefinitions.Values) GenerateClass(context, definition);
	}

	private static void GenerateClass(SourceProductionContext context, ClassDefinition definition) {
		var memberCode = new StringBuilder();
		foreach (var memberDefinition in definition.MemberDefinitions) {
			var nodeName = memberDefinition.Name.TrimStart('_');
			nodeName = nodeName.Substring(0, 1).ToUpper() + nodeName.Substring(1);

			memberCode.AppendLine($$"""
			                                {{memberDefinition.Name}} = GetNode<{{memberDefinition.Type}}>("%{{nodeName}}");
			                        """);
		}

		var usingCode = new StringBuilder();
		foreach (var namespaceName in definition.UsingNamespaceName) usingCode.AppendLine($"using {namespaceName};");

		// Build up the source code
		var code = $$"""
		             // <auto-generated/>

		             using System;
		             {{usingCode}}

		             namespace {{definition.NamespaceName}};

		             partial class {{definition.ClassName}}
		             {
		                private void BindFields() {
		             {{memberCode}}
		                }
		             }

		             """;
		context.AddSource($"{definition.ClassName}.Binder.g.cs", SourceText.From(code, Encoding.UTF8));
	}
}