using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace GenUtilities;

[Generator]
public class GroupGenerator : IIncrementalGenerator {
    private const string Namespace = "GenUtilities";
    private const string ClassName = "Groups";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var projectFile = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith("project.godot"))
            .Select((file, token) => file.GetText(token))
            .Collect();

        context.RegisterSourceOutput(projectFile, GenerateCode);
    }

    private void GenerateCode(SourceProductionContext context, ImmutableArray<SourceText?> texts) {
        var memberCode = new StringBuilder();
        foreach (var text in texts) {
            if (text == null) continue;
            var content = text.ToString();
            var groups = GetGroups(content);
            var fields = groups.Select(keyData =>
                $"""
                    /// <summary>
                    /// {keyData.Value}
                    /// </summary>
                    public static StringName {keyData.Key} = "{keyData.Key}"; 
                 """);

            foreach (var field in fields) memberCode.AppendLine(field);
        }

        var code = $$"""
                     // <auto-generated/>

                     using System;
                     using Godot;

                     namespace {{Namespace}};

                     partial class {{ClassName}}
                     {
                     {{memberCode}}
                     }

                     """;
        context.AddSource($"{Namespace}.{ClassName}.g.cs", SourceText.From(code, Encoding.UTF8));
    }

    private static Dictionary<string, string> GetGroups(string content) {
        var result = new Dictionary<string, string>();
        var foundSection = false;
        foreach (var line in content.Split(['\n'])) {
            if (line.Equals("[global_group]")) {
                foundSection = true;
            } else if (line.StartsWith("[") && foundSection) break;

            if (!foundSection) continue;

            var keyValue = line.Split(['='], 2);
            if (keyValue.Length == 2) result[keyValue[0].Trim()] = keyValue[1].Trim();
        }

        return result;
    }
}
