using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;

namespace GenUtilities;

[Generator]
public class MetaGenerator : IIncrementalGenerator {
    private const string RegisterMetaAttribute =
        """
        namespace GenUtilities;

        [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface)]
        public class RegisterMetaAttribute : System.Attribute { }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("RegisterMetaAttribute.g.cs", RegisterMetaAttribute));

        var typesProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            "GenUtilities.RegisterMetaAttribute",
            static (node, _) => node is ClassDeclarationSyntax or InterfaceDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(typesProvider, static (spc, typeSymbol) => {
            var isPartial = typeSymbol.DeclaringSyntaxReferences
                .Select(r => r.GetSyntax())
                .OfType<TypeDeclarationSyntax>()
                .Any(s => s.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)));

            if (!isPartial) {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("MG001", "Type must be partial",
                        $"Type '{typeSymbol.Name}' must be declared with the 'partial' keyword to have members generated.",
                        "Generator", DiagnosticSeverity.Error, true),
                    typeSymbol.Locations.FirstOrDefault()));
                return;
            }

            spc.AddSource($"{typeSymbol.ToDisplayString()}.g.cs", GeneratePartialSource(typeSymbol));
        });
    }

    private static string GeneratePartialSource(INamedTypeSymbol typeSymbol) {
        var ns = typeSymbol.ContainingNamespace;
        var typeName = typeSymbol.Name;
        var typeKeyword = typeSymbol.TypeKind switch {
            TypeKind.Interface => "interface",
            TypeKind.Class when typeSymbol.IsRecord => "record",
            TypeKind.Class => "class",
            _ => "" // Should not happen based on the provider filter
        };

        if (string.IsNullOrEmpty(typeKeyword)) {
            return string.Empty;
        }

        var methods =
            $$"""
                  public static {{typeName}}? GetImpl(Godot.Node node) {
                      if (node is {{typeName}} takeDamage) return takeDamage;
                      var meta = node.GetMeta("{{typeName}}");
                      if (meta.VariantType == Godot.Variant.Type.Nil) return null;
                      return meta.Obj as {{typeName}};
                  }

                  public static void SetImpl(Godot.Node node, Godot.Variant impl) {
                      if (impl.Obj is {{typeName}}) {
                          node.SetMeta("{{typeName}}", impl);
                      } else {
                          Godot.GD.PushError($"Impl '{impl}' is not {{typeName}} for '{node}'");
                      }
                  }
              """;

        string content;
        if (ns.IsGlobalNamespace) {
            content =
                $$"""
                  public partial {{typeKeyword}} {{typeName}}
                  {
                  {{methods}}
                  }
                  """;
        } else {
            content =
                $$"""
                  namespace {{ns.ToDisplayString()}}
                  {
                      public partial {{typeKeyword}} {{typeName}}
                      {
                  {{methods.Replace("\n", "\n        ")}}
                      }
                  }
                  """;
        }

        return
            $$"""
              // <auto-generated/>
              #nullable enable
              using Godot;

              {{content}}
              """;
    }
}
