using System.Collections.Generic;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;

namespace GenUtilities;

[Generator]
public class SceneGenerator : IIncrementalGenerator {
	private const string Namespace = "GenUtilities";


	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var scenes = context.AdditionalTextsProvider
			.Where(text => text.Path.EndsWith(".tscn"));

		context.RegisterSourceOutput(context.CompilationProvider.Combine(scenes.Collect()).Combine(context.AnalyzerConfigOptionsProvider),
			(ctx, t) => GenerateCode(ctx, t.Left.Left, t.Left.Right, t.Right));
	}

	private void GenerateCode(
		SourceProductionContext context,
		Compilation compilation,
		IEnumerable<AdditionalText> scenes,
		AnalyzerConfigOptionsProvider optionsProvider) {
		optionsProvider.GlobalOptions.TryGetValue("build_property.projectdir", out var projectDirectory);

		var allMethods = new StringBuilder();
		foreach (var scene in scenes) {
			var directory = Path.GetDirectoryName(scene.Path);
			var name = Path.GetFileNameWithoutExtension(scene.Path);
			var relativePath = scene.Path.Replace(projectDirectory ?? "", "").Replace("\\", "/");
			allMethods.AppendLine(
				$$"""
				  	public static T New{{name.SnakeToCamelCase()}}<T>() where T : Node {
				  		var packedScene = GD.Load<PackedScene>("res://{{relativePath}}");
				  		return packedScene.Instantiate<T>();
				  	}
				  """);
		}

		var code =
			$$"""
			  // <auto-generated/>
			  
			  using System;
			  using Godot;

			  namespace {{Namespace}};

			  class Scenes
			  {
			  {{allMethods}}
			  }
			  """;
		context.AddSource("GenUtilities.Scenes.g.cs", SourceText.From(code, Encoding.UTF8));
	}
}