using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;

namespace GenUtilities;

[Generator]
public class SingletonGenerator : IIncrementalGenerator {
    private const string SingletonAttribute =
        """
        namespace GenUtilities;

        [System.AttributeUsage(System.AttributeTargets.Class)]
        public class SingletonAttribute : System.Attribute { }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("SingletonAttribute.g.cs", SingletonAttribute));

        var typesProvider = context.SyntaxProvider.ForAttributeWithMetadataName(
            "GenUtilities.SingletonAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(typesProvider, static (spc, typeSymbol) => {
            var isPartial = typeSymbol.DeclaringSyntaxReferences
                .Select(r => r.GetSyntax())
                .OfType<TypeDeclarationSyntax>()
                .Any(s => s.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)));

            if (!isPartial) {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("MG001", "Type must be partial",
                        $"Type '{typeSymbol.Name}' must be declared with the 'partial' keyword to have members generated.",
                        "Generator", DiagnosticSeverity.Error, true),
                    typeSymbol.Locations.FirstOrDefault()));
                return;
            }

            spc.AddSource($"{typeSymbol.ToDisplayString()}.g.cs", GeneratePartialSource(typeSymbol));
        });
    }

    private static string GeneratePartialSource(INamedTypeSymbol typeSymbol) {
        var ns = typeSymbol.ContainingNamespace;
        var typeName = typeSymbol.Name;

        var methods =
            $$"""
              public static {{typeName}} GetOrCreate() {
                  if (_instance != null) return _instance;
                  _instance = Scenes.New{{typeName}}<{{typeName}}>();
                  ((SceneTree)Engine.GetMainLoop()).Root.AddChild(_instance);
                  return _instance;
              }
              """;

        string content;
        if (ns.IsGlobalNamespace) {
            content =
                $$"""
                  public partial class {{typeName}}
                  {
                      private static {{typeName}}? _instance;
                      public static {{typeName}} Instance => GetOrCreate();
                  {{methods}}
                  }
                  """;
        } else {
            content =
                $$"""
                  namespace {{ns.ToDisplayString()}}
                  {
                      public partial class {{typeName}}
                      {
                            private static {{typeName}}? _instance;
                            public static {{typeName}} Instance => GetOrCreate();
                  {{methods.Replace("\n", "\n        ")}}
                      }
                  }
                  """;
        }

        return
            $$"""
              // <auto-generated/>
              #nullable enable
              using Godot;
              using GenUtilities;
              
              {{content}}
              """;
    }
}
