using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GenUtilities;

[Generator]
public class SyncGenerator : IIncrementalGenerator {
    private const string Namespace = "GenUtilities";
    private const string AttributeName = "Sync";

    private const string AttributeSourceCode = $@"// <auto-generated/>
using Godot;

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field)]
    public class {AttributeName} : System.Attribute
    {{
        public SceneReplicationConfig.ReplicationMode ReplicationMode {{ get; set; }} = SceneReplicationConfig.ReplicationMode.Always;
        public bool Spawn {{ get; set; }} = true;
    }}
}}";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "SyncAttribute.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        var propertyProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => GetDeclarationForSourceGen(ctx))
            .Where(t => t.attributeFound)
            .SelectMany((t, _) => t.Item1);

        context.RegisterSourceOutput(context.CompilationProvider.Combine(propertyProvider.Collect()),
            (ctx, value) => GenerateCode(ctx, value.Left, value.Right));
    }

    private static (IEnumerable<MemberDeclarationSyntax>, bool attributeFound) GetDeclarationForSourceGen(
        GeneratorSyntaxContext context) {
        var classSyntax = (ClassDeclarationSyntax)context.Node;
        var members = classSyntax.Members;
        var foundMembers = members.Select(member => IsBindAttributeOnMember(context.SemanticModel, member))
            .Where(syntax => syntax != null)
            .ToList();
        return (foundMembers!, foundMembers.Count > 0);
    }


    private static MemberDeclarationSyntax? IsBindAttributeOnMember(SemanticModel model,
        MemberDeclarationSyntax declarationSyntax) {
        foreach (var attributeSyntax in declarationSyntax
                     .AttributeLists
                     .SelectMany(attributeListSyntax => attributeListSyntax.Attributes)) {
            if (model.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue;

            var attributeName = attributeSymbol.ContainingType.ToDisplayString();
            if (attributeName == $"{Namespace}.{AttributeName}")
                return declarationSyntax;
        }

        return null;
    }

    private class ClassDefinition {
        public string NamespaceName { get; set; } = "";
        public string ClassName { get; set; } = "";
        public HashSet<string> UsingNamespaceName { get; set; } = [];

        public List<MemberDefinition> MemberDefinitions { get; } = [];
    }

    private class MemberDefinition {
        public string Type { get; set; } = "";
        public string Name { get; set; } = "";
        public bool Spawn { get; set; }
        public string ReplicationMode { get; set; } = "";
    }

    private void GenerateCode(SourceProductionContext context, Compilation compilation,
        ImmutableArray<MemberDeclarationSyntax> members) {
        Dictionary<string, ClassDefinition> classDefinitions = [];

        foreach (var member in members)
            if (member.Parent is ClassDeclarationSyntax classDeclarationSyntax) {
                var semanticModel = compilation.GetSemanticModel(classDeclarationSyntax.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(classDeclarationSyntax) is not INamedTypeSymbol classSymbol)
                    continue;

                var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
                var className = classDeclarationSyntax.Identifier.Text;
                var key = $"{namespaceName}.{className}";
                if (!classDefinitions.ContainsKey(key)) classDefinitions[key] = new ClassDefinition();

                var classDefinition = classDefinitions[key];
                classDefinition.ClassName = className;
                classDefinition.NamespaceName = namespaceName;
                if (member is FieldDeclarationSyntax field) {
                    var variable = field.Declaration.Variables[0];

                    // Get the Type of the field.
                    if (semanticModel.GetDeclaredSymbol(variable) is not IFieldSymbol fieldSymbol) continue;

                    var memberDefinition = new MemberDefinition {
                        Name = fieldSymbol.Name,
                        Type = fieldSymbol.Type.Name
                    };
                    classDefinition.MemberDefinitions.Add(memberDefinition);
                    classDefinition.UsingNamespaceName.Add(fieldSymbol.Type.ContainingNamespace.ToDisplayString());
                    // Check if the field has the [Sync] attribute and read the properties from the attribute.
                    if (fieldSymbol.GetAttributes().Any(attr => attr.AttributeClass?.Name == "Sync")) {
                        var syncAttribute = fieldSymbol.GetAttributes()
                            .First(attr => attr.AttributeClass?.Name == "Sync");
                        memberDefinition.Spawn = syncAttribute.NamedArguments
                            .Any(pair => pair.Key == "Spawn" && (bool)(pair.Value.Value ?? false));
                        memberDefinition.ReplicationMode = string.Empty;
                        if (syncAttribute.ApplicationSyntaxReference?.GetSyntax() is AttributeSyntax attributeSyntax) {
                            var argument = attributeSyntax.ArgumentList?.Arguments
                                .FirstOrDefault(a => a.NameEquals?.Name.Identifier.Text == "ReplicationMode");
                            if (argument != null) {
                                memberDefinition.ReplicationMode = argument.Expression.ToString();
                            }
                        }
                    }
                } else if (member is PropertyDeclarationSyntax property) {
                    if (semanticModel.GetDeclaredSymbol(property) is not IPropertySymbol propertySymbol) continue;

                    var memberDefinition = new MemberDefinition {
                        Name = propertySymbol.Name,
                        Type = propertySymbol.Type.Name
                    };
                    classDefinition.MemberDefinitions.Add(memberDefinition);
                    classDefinition.UsingNamespaceName.Add(propertySymbol.Type.ContainingNamespace.ToDisplayString());
                }
            }

        foreach (var definition in classDefinitions.Values) GenerateClass(context, definition);
    }

    private static void GenerateClass(SourceProductionContext context, ClassDefinition definition) {
        var memberCode = new StringBuilder();
        // var propertyCode = new StringBuilder();
        var methodCode = new StringBuilder();
        var eventCode = new StringBuilder();
        foreach (var memberDefinition in definition.MemberDefinitions) {
            var fieldName = memberDefinition.Name;
            var propertyName = fieldName.TrimStart('_');
            propertyName = propertyName.Substring(0, 1).ToUpper() + propertyName.Substring(1);

            // Sadly not works because of racing conditions.
//             propertyCode.AppendLine(
//                 $$"""
//                     [Export]
//                     public {{memberDefinition.Type}} {{propertyName}} {
//                       get => {{fieldName}};
//                       set => Set{{propertyName}}(value);
//                     }
//                   """);
//             
            eventCode.AppendLine(
                $$"""
                    public event Action<{{memberDefinition.Type}}>? {{propertyName}}Changed;
                  """);

            memberCode.AppendLine(
                $$"""
                  config.AddProperty(new NodePath(".:{{propertyName}}"));
                  """);

            if (memberDefinition.Spawn) {
                memberCode.AppendLine(
                    $$"""
                      config.PropertySetSpawn(".:{{propertyName}}", true);
                      """);
            }

            if (memberDefinition.ReplicationMode != string.Empty) {
                memberCode.AppendLine(
                    $$"""
                      config.PropertySetReplicationMode(".:{{propertyName}}", {{memberDefinition.ReplicationMode}});
                      """);
            }

            methodCode.AppendLine(
                $$"""
                    private void Set{{propertyName}}({{memberDefinition.Type}} value) {
                        if (value == {{fieldName}}) return;
                        
                        log.Debug($"Set {{propertyName}} to {value}");
                        {{fieldName}} = value;
                        {{propertyName}}Changed?.Invoke(value);
                    }
                  """);
        }

        var usingCode = new StringBuilder();
        foreach (var namespaceName in definition.UsingNamespaceName) usingCode.AppendLine($"using {namespaceName};");
        
        // Build up the source code
        var code = $$"""
                     // <auto-generated/>
                     #nullable enable

                     using Godot;
                     {{usingCode}}

                     namespace {{definition.NamespaceName}};

                     public partial class {{definition.ClassName}}
                     {
                        {{eventCode}}

                        private void StartSync() {
                            var sync = new MultiplayerSynchronizer();
                            sync.SetMultiplayerAuthority(GetMultiplayerAuthority());
                            sync.Name = GetType().Name;
                            var config = new SceneReplicationConfig();
                            {{memberCode}}
                            sync.SetReplicationConfig(config);
                            AddChild(sync);
                        }
                        
                        {{methodCode}}
                     }

                     """;
        context.AddSource($"{definition.ClassName}.Sync.g.cs", SourceText.From(code, Encoding.UTF8));
    }
}
